import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js Tutorial",
  description: "Generated by create next app",
};

// This is layout page. What component is declared here is shared in everywhere

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <nav className="text-2xl text-primary">This is Navbar</nav> */}
        <NavBar />
        <main className="px-8 py-20 max-w-6xl mx-auto">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}

//  In the provided Next.js code, the children prop in the RootLayout function represents the content of
//  the pages that are wrapped by this layout. When you define a layout component like RootLayout,
//  Next.js will automatically pass the page content (the component tree of the current page) to this children prop.
