import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js Tutorial",
  description: "Generated by create next app",
};

// This is layout page. What component is declared here is shared in everywhere

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <nav className="text-2xl text-primary">This is Navbar</nav> */}
        <NavBar />
        {children}
      </body>
    </html>
  );
}
